version: '3.2'
services:
  db:
    container_name: 'database'
    image: postgres
    environment:
      - POSTGRES_DB=${databaseName}
      - POSTGRES_USER=${username}
      - POSTGRES_PASSWORD=${password}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always


volumes:
  db: